name: troona
description: "A premium offline music player with a glassmorphism design."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # --- CORE ARCHITECTURE ---
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  rxdart: ^0.28.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  dartz: ^0.10.1
  equatable: ^2.0.8
  go_router: ^17.1.0
  path_provider: ^2.1.5
  logger: ^2.6.2

  # --- AUDIO ENGINE ---
  just_audio: ^0.10.4
  audio_service: ^0.18.18
  audio_session: ^0.2.2

  # --- STORAGE & INDEXING ---
  on_audio_query_pluse: ^3.0.6
  device_info_plus: ^12.3.0
  permission_handler: ^11.3.0
  isar_plus: ^1.2.2
  shared_preferences: ^2.5.4

  # --- UI & DESIGN ---
  eva_icons_flutter: ^3.1.0
  flutter_screenutil: ^5.9.3
  palette_generator_master: ^1.0.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- CODE GENERATION ---
  injectable_generator: ^2.12.1
  build_runner: ^2.12.2

flutter:
  uses-material-design: true
