name: troona
description: "A premium offline music player with a glassmorphism design."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # --- CORE ARCHITECTURE ---
  get_it: ^9.2.1

  # --- AUDIO ENGINE ---
  just_audio: ^0.10.4
  audio_service: ^0.18.18

  # --- STORAGE & INDEXING ---
  on_audio_query_pluse: ^3.0.6

  # --- UI & DESIGN ---
  eva_icons_flutter: ^3.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
